### ISSUE TITLE
TIP: Implement solidity fallback function logic  in transferContract transaction

### ISSUE THREAD

**Issue by zhangheng1536** [tronprotocol/TIPs#11]
## Simple Summary

Trigger fallback function for a smart contract, when we transfer trx to it.

## Abstract

Fallback Function (from Ethereum)

> A contract can have exactly one unnamed function. This function cannot have arguments, cannot return anything and has to have external visibility. It is executed on a call to the contract if none of the other functions match the given function identifier (or if no data was supplied at all).
> Furthermore, this function is executed whenever the contract receives plain Ether (without data). Additionally, in order to receive Ether, the fallback function must be marked payable. If no such function exists, the contract cannot receive Ether through regular transactions.
> It does not trigger a fallback function for the smart contract,When we transfer trx to a smart contract on tron mainet. And we are allowed to use transferContract sending trx to a smart contract account even with a non-payable type fallback function in it.

## Motivation

For some specific contracts, such as ICO, developers would like to record msg.sender, msg.value information in it.  Fallback function would be a proper way to record all these data. And it would also be a convenient way for contract to handle different logic related to trx transferring. 

## Specification

A normal transfer can trigger a fallback function for a smart contract.

**Comment by taihaofu** [comment]
@zhangheng1536 , We see several similar requirements from dapp developer about this fallback issue. See https://github.com/tronprotocol/java-tron/issues/1677

It is related to two types of contracts, transferContract and transferAssetContract, those are Tron system contracts. 

Ethereum can trigger fallback while transfer eth because every transaction would invoke evm and be able to execute its code if the address is a contract address. 

On the contract, transferContract is a system Contract in tron and it is not designed for smart contract execution.

If we decide to implement these logics, we probably need to do:

1. add feelimit in transferContract/transferAssetContract, so that we can use energy in these two contracts.

2. check if the transferTo address is a contract address, if so turn it from execute precompile contract logic to triggerSmart contract logic.

3. transferContract could fail due to exception in fallback, so change the logic for exception.

**Comment by taihaofu** [comment]
@zhangheng1536 , personally I have some doubt about whether we should implement this or not. 

1. transferContract/transferAssetContract are two excellent ways to transfer trx and tokens. People would use less money for transferring. We should not break this and not force it to smart contract process. 
 
Currently we only need bandwidth as resource for system contracts. We should not introduce extra energy to the process, which is really expensive. 

2. Consider of exchanges, such as gateio. Current transaction fee is 0.1trx, and it would probably be added to 1trx or 2trx according to trx/energy rate if we use energy in it. It is not friendly to our developers and users.

**Comment by taihaofu** [comment]
For ICO, we suggest to use some other ways to trigger fallback when transfer trx. 

Developers can set up an entry for ICO, and use trigger smart contract api for recording in fallback purpose. This alternative way can do the same as what ethereum does.

**Comment by titscrypto** [comment]
> @zhangheng1536 , personally I have some doubt about whether we should implement this or not.
> 
> 1. transferContract/transferAssetContract are two excellent ways to transfer trx and tokens. People can use less money for transferring. We should not break this and not force it to smart contract process.
> 
> Currently we only need bandwidth as resource for system contracts. We should not introduce extra energy to the process, which is really expensive.
> 
> 1. Considering of exchanges, such as gateio, current transaction fee is 0.1trx, and it would probably be added to 1trx or 2trx according to trx/energy rate if we count energy within it. It is not friendly to our developers and users.

I do not understand that argument You can provide trigering fallback bunction as an alternative to  transferContract/transferAssetContract not as a replacement. 

The fact that fallback is not suported breaks compatibility with EVM. 

Tron do **NOT support evm specification** as it is created now and that is very dangerous since it claims it does.

**Comment by taihaofu** [comment]
@titscrypto, we already has a way to trigger fallback function. TriggerSmartContract fully matches what etheream does and spend energy(gas) as evm specification, which means you can call fallback using TriggerSmartContract just as what you do on etheream. We would like to regard transferContract/transferAssetContract as extensions for now. The arguments are more consider about the user experience for the exchanges and current dapp developers and it suggest we should not add extra functionality for transferContract/transferAssetContract.
