### ISSUE TITLE
Discussion: Can't we just disable TRC10 and stop the scammers instead of lowering free bandwidth and increasing fees

### ISSUE THREAD

**Issue by amhoba** [tronprotocol/tips#365]
As I stated right here: https://github.com/tronprotocol/tips/issues/320#issuecomment-1016621545

Can't we Just DISABLE the creation of more TRC10 tokens?
And just keep TRX?
And revert all those proposals that have been created so far to just address this simple problem (#286 #320)?

Seems like TRC10 tokens (except TRX) do not have much use case, and they can be easily abused (unless they have intrinsic value like TRX, which costs abusers money).

**Comment by vivian-kang** [comment]
Thanks for your suggestion. 
For free bandwidth, 1500 Bandwidth can afford almost 5 or 6 free transactions, It should be OK for daily usage for normal users. but as for frequency transaction, even though the original 5000 free bandwidth, it also cannot meet all users demand , so I will suggest to stake TRX for resource, it not only can get resource but also can make Tron system more stable.

**Comment by amhoba** [comment]
@vivian-kang No Im done with this. Its been 7 days and nobody has ever made a real technical comment here. What a decentralized system this is? Where is democracy? Where is collaboration?

Its ridiculous that nobody is using TRC10 and you are limiting developers for the sake of preventing scammers.
Just disable TRC10 and all your problems are gone... But I don't think this is gonna happen, Tron is left to die when Justin left it...

Im just thinking about the next tron fork... or I may switch to other crypto.

**Comment by vivian-kang** [comment]
TRC10 token cannot be replaced by TRC20 token, it has its own value and uses, because it does not need to execute in TVM, so as governance token, TRC10 may be a good choice，for example, BTT.  So I think fully disable TRC10 is not an option.
And from the statistics：https://tronscan.org/#/data/stats/txOverviewStatsType, the volume of TRC10 transactions have already dropped off, but TRC20 and TRX transactions are unaffected.

**Comment by hitlxy** [comment]
Disable TRC10 can solve the scammer issue, but all projects based on TRC10 will be down. 
And another solution from TRC10 aspect is "Only forbid deploying new TRC10 tokens but the TRC10 feature is still available".  and the issue of this solution is scammers also can use the old TRC10 tokens to send lots of fraudulent transactions because of the low fee. 

 So it may be hard to realization.

**Comment by hitlxy** [comment]
how to just keep the valuable TRC10 tokens,  hard-coded ?

**Comment by amhoba** [comment]
Yes. Hardcode the governance tokens and disable the rest.

**Comment by hitlxy** [comment]
except fraudulent project, some valuable projects should not been banned. but it is difficult to identify which one is fraudulent or valuable.

**Comment by amhoba** [comment]
If I know it right, TRC10 is being used mostly for governance tokens (that are agreed upon creation by core devs).
If anyone other than core dev needs to create a token, they can move on to TRC20, right?
This way we can have valuable projects both in TRC10 and TRC20. Fraudulent projects will be forced to move to TRC20 which costs them and they can not use it to spam the network.

**Comment by hitlxy** [comment]
Actually I think hard-coded is not a good choice, it is inconsistent with decentralization, it should not been used in public chain.

**Comment by amhoba** [comment]
> it is inconsistent with decentralization

I'll close this issue. Looks like this conversation will be going nowhere...
