### ISSUE TITLE
TRC-484:TRON liquidity staking and resource market

### ISSUE THREAD

**Issue by raymondliu0711** [tronprotocol/tips#484]
```
tip: 484
title: Smart Contract Standard for TRX liquidity staking and resource market 
author: raymondliu0711
discussions-to: https://github.com/tronprotocol/tips/issues/484
status: Draft
type: Standards Track
category: TRC
created: 2022-11-28
requires: TIP-271, TIP-467
```

## Simple Summary

This post proposes a standard for smart-contracts to implement TRX-staking and resource-rental markets after the adoption of TIP-271 and TIP-467. With this standard, this kind of markets could be integrated by other DeFi protocols.

## Abstract

When TRX is frozen to participate in on-chain governance, it is not liquid and cannot be combined with ecosystems of smart contract, which greatly limits the usage scenarios of TRX freezing, and discourages TRX holders from freezing TRX and voting to participate in TRON governance.

With the adoption of TIP-271 and TIP-467, freezing, voting and delegating resource operations can be implemented with smart contracts. Furthermore, smart-contracts can be build to provide TRX liquidity staking and resource rental. This kind of market would increase the flexibility and improve the revenue of TRX staking, and allow the community to regulate the price of energy and bandwidth resources in a more flexible way.

So, We propose a standard for smart contract to implement this market. Adopting the same specification facilitates the integration of other Defi protocols.

## Motivation

Currently, TRON’s DPoS scheme is only implemented natively by the chain, and the TRX in stake cannot be transferred to others, which is not liquid and cannot be integrated with the contract ecosystem. Users need to unfreeze TRX and wait for a delay before they can transfer these TRX. During the unfreezing period, users do not hold their original voting revenue and free resources.

Staking TRX into TRC-20 tokens, where the staked TRX can share in the SR voting revenue, solves these problems. Users of the tokens share voting revenue during the staking period and can transfer the directly when transferring assets, without the need to unfreeze TRX. At the same time, the tokens also comply well with TRON’s existing ecosystem.

In addition, the TRON network currently provides only 27 free energy for 1 staked TRX, and 518 TRX to get the 14,000 free energy needed for a standard TRC20 transfer, which means a lot of TRX needs to be staked for users with the consistent need of large amounts energy, and it is inconvenient for transient users with needs of small amounts energy to stake and unstake TRX frequently. As you can see from the actual data, TRON has a very high percentage of burning TRX in its transactions.

After tokenizing staked TRX, it will also get free resources (energy/bandwidth), and if they implement a resource leasing mechanism in it, anyone can lease energy from it, and the energy pricing can be flexibly and dynamically adjusted according to the chain and ecology.

Staking TRX Tokenization Combined with the energy market would reduce the obstacle of TRX staking and help to increase the TRX staking rate of TRON; it would also achieve self-balancing of energy supply and demand and help to promote the development of the TRON ecology.

Therefore, it is necessary for us to provide a standard for such contracts, as TRC-484, so that their implementations can be integrated by other DeFi protocols in the community.

## Specification

We propose a standard, TRC-484, for decentralized TRX liquidity stake and resource rental market that consists of the following main points.

1. stake tokenization, and the token can be combined into TRON ecology.
2. provide an automatically adjustable resource rental market.
3. any TRX holder can participate in TRON governance by depositing TRX through the standard, instead of on-chain staking.

The standard TRC-484 is as follows.
TRX holders deposit TRX to obtain a corresponding number of pass-through TRC-484 tokens. TRC-484 tokens are freely circulating and convertible with TRX, and can participate in other ecology of the TRON as a standard TRC-20 token.

Holders of TRC-484 tokens share the revenue, which comes from two sources: on-chain frozen TRX voting rewards and revenue from resource rental.

The implementation should be governed by the DAO composed of TRC-484 token holders, and the behavior should include: electing SRs to vote for, adjusting the price strategy of resource rental, etc. The DAO governance will enable the flexible adjustment of resource prices on the chain.

The specification below is just a simple draft and it needs further discussion. We are working on improving it, and all kinds of opinions are welcome.

**Every TRC-484 compliant contract must implement the `TRC484` and `TRC20` interfaces**

```solidity
interface TRC484 /* is TRC20 */ {
    
    /// @dev Deposit `msg.value` TRX to the contract and receive `amount` of TRC484 token.
    function deposit() public payable returns (uint256 amount);
    
    /// @dev Exit `_value` TRC484 token and receive `trxAmount` of TRX.
    function exit(uint256 _value) public returns (uint256 trxAmount);
    
    /// @dev Exit for exact `_trxValue` TRX and pays `tokenAmount` of TRC484 token.
    function exitExact(uint256 _trxValue) public returns (uint256 tokenAmount);
    
    /// @dev Rent `_type` resources of `_amount` TRX for `_period` time units and pays `msg.value` TRX for the rent, and an id `rentId` is assigned to the rent for redeem.
    function rentResources(uint256 _type, uint256 _amount, uint256 _period) public payable returns (uint256 rentId);
    
    /// @dev Repay the rent of `_rentId`, the return value `success` indicates if it is success.
    function repayResources(uint256 _rentId) public returns (bool success);
    
}
```

## Backward Compatibility

There are no backward compatibility issues.

## Implementation

There is no detailed implementation so far, but the basic concepts and components of the standard can be indicated in the figure below.

![TRC-484](https://user-images.githubusercontent.com/91414247/205075944-1b914702-dd38-46f5-93f2-17ca6f220fe9.png)

TRX holders can deposit TRX to the TRC-484 contract and get TRC-484 token, meanwhile, TRC-484 token holders can exit TRX with TRC-484 token from it. TRC-484 token holders compose the DAO and govern the contract, they can also participate in the TRON ecosystem as TRC-484 token can serve as a standard TRC-20 token.

The TRC-484 contract freezes the deposited TRX, votes for SRs, provides resources to and collects rent from resourceUsers, and distributes the voting and rental rewards to TRC-484 token holders.

**Comment by otakuinny** [comment]
@raymondliu0711, in other words you had an idea to make money off of tron resource rental market and you want to change the entire current resources model to fit your needs, right? :laughing: 

This is easily one of the worst proposals I have heard to fit the business need of one individual. **The current resources model can use some flexibility but not by further tokenizing TRX. For god's sakes stop creating tokens on top of tokens. The tip https://github.com/tronprotocol/tips/issues/467 already is working on changing the resources model and it has a few changes that addresses almost all of your concerns above.**

Please go through existing tips before creating new ones.

**Comment by raymondliu0711** [comment]
@otakuinny I noticed that the resource model has been adjusted in #467 and some instructions have been added to the TVM to allow contract accounts to perform some of the operations in the new stake system as well as EOA accounts.
However, these are only upgrades and innovations in the chain itself. The TRON network does not provide stake tokenization and liquidity design for the old and new stake systems. This is the main problem that this proposal is trying to solve.
The discussion is open and we welcome your opinions.

**Comment by zhaohong** [comment]
> @raymondliu0711, in other words you had an idea to make money off of tron resource rental market and you want to change the entire current resources model to fit your needs, right? 😆
> 
> This is easily one of the worst proposals I have heard to fit the business need of one individual. **The current resources model can use some flexibility but not by further tokenizing TRX. For god's sakes stop creating tokens on top of tokens. The tip #467 already is working on changing the resources model and it has a few changes that addresses almost all of your concerns above.**
> 
> Please go through existing tips before creating new ones.

The TRC is to implement a decentralized energy market (DAPP) based on the idea of #467 , that anyone can implement such a market.

**Comment by otakuinny** [comment]
> @otakuinny I noticed that the resource model has been adjusted in #467 and some instructions have been added to the TVM to allow contract accounts to perform some of the operations in the new stake system as well as EOA accounts. However, these are only upgrades and innovations in the chain itself. The TRON network does not provide stake tokenization and liquidity design for the old and new stake systems. This is the main problem that this proposal is trying to solve. The discussion is open and we welcome your opinions.

I'm so sick and tired of hearing about resource rental market. Renting out tron resources is a by-product of an address being able to delegate resources to another address. Too much attention is being paid to the resource rental process. Instead of encouraging it with peoposals like these, we should be discouraging it. Renting resources prevents users from burning trx which contributes to trx inflation which results in lower price. It is actually healthy for TRON to burn trx. This will decrease the circulating supply and the resultant price increase will attract more people to the chain. And another thing, right now the majority of daily transactions are just spam and/or scam transactions. All these scammers rent energy which is why they are able to make so many transactions. I don't understand why you want to make it even more easier for scammers to send more scam transactions while at the same time pushing the price of trx lower on account of not burning any trx for transactions. 

There is already a vibrant rental Markey and every Tom, Dick and Harry sells their energy on Telegram and other places. There's no need to make it any more easier for scammers to rent energy than it is right now.

Please stop with proposals like these that hurt tron and try to think about how you can make TVM better. Seeing a lot of errors lately.

**Comment by raymondliu0711** [comment]
> > @otakuinny I noticed that the resource model has been adjusted in #467 and some instructions have been added to the TVM to allow contract accounts to perform some of the operations in the new stake system as well as EOA accounts. However, these are only upgrades and innovations in the chain itself. The TRON network does not provide stake tokenization and liquidity design for the old and new stake systems. This is the main problem that this proposal is trying to solve. The discussion is open and we welcome your opinions.
> 
> I'm so sick and tired of hearing about resource rental market. Renting out tron resources is a by-product of an address being able to delegate resources to another address. Too much attention is being paid to the resource rental process. Instead of encouraging it with peoposals like these, we should be discouraging it. Renting resources prevents users from burning trx which contributes to trx inflation which results in lower price. It is actually healthy for TRON to burn trx. This will decrease the circulating supply and the resultant price increase will attract more people to the chain. And another thing, right now the majority of daily transactions are just spam and/or scam transactions. All these scammers rent energy which is why they are able to make so many transactions. I don't understand why you want to make it even more easier for scammers to send more scam transactions while at the same time pushing the price of trx lower on account of not burning any trx for transactions.
> 
> There is already a vibrant rental Markey and every Tom, Dick and Harry sells their energy on Telegram and other places. There's no need to make it any more easier for scammers to rent energy than it is right now.
> 
> Please stop with proposals like these that hurt tron and try to think about how you can make TVM better. Seeing a lot of errors lately.

Now freezing to get energy is much cheaper than burning. Spam apps basically come from resource markets, but the current resource markets are normally p2p model, which is not flexible for price adjustment.

The most critical point of this proposal is to propose a standard how to how to implement a resource rental market with smart contract, that make TRX liquidity staking can be tokenized. The resource market is just a by-product of it. Also, the standard resource market can be integrated with DeFi applications. After this kind of resource market supports energy renting, the standard smart contract can adjust price more reasonably than current p2p ones. Energy renting will also promote a more prosperous ecology which can make TRON better.

**Comment by otakuinny** [comment]
> > > @otakuinny I noticed that the resource model has been adjusted in #467 and some instructions have been added to the TVM to allow contract accounts to perform some of the operations in the new stake system as well as EOA accounts. However, these are only upgrades and innovations in the chain itself. The TRON network does not provide stake tokenization and liquidity design for the old and new stake systems. This is the main problem that this proposal is trying to solve. The discussion is open and we welcome your opinions.
> > 
> > 
> > I'm so sick and tired of hearing about resource rental market. Renting out tron resources is a by-product of an address being able to delegate resources to another address. Too much attention is being paid to the resource rental process. Instead of encouraging it with peoposals like these, we should be discouraging it. Renting resources prevents users from burning trx which contributes to trx inflation which results in lower price. It is actually healthy for TRON to burn trx. This will decrease the circulating supply and the resultant price increase will attract more people to the chain. And another thing, right now the majority of daily transactions are just spam and/or scam transactions. All these scammers rent energy which is why they are able to make so many transactions. I don't understand why you want to make it even more easier for scammers to send more scam transactions while at the same time pushing the price of trx lower on account of not burning any trx for transactions.
> > There is already a vibrant rental Markey and every Tom, Dick and Harry sells their energy on Telegram and other places. There's no need to make it any more easier for scammers to rent energy than it is right now.
> > Please stop with proposals like these that hurt tron and try to think about how you can make TVM better. Seeing a lot of errors lately.
> 
> Now freezing to get energy is much cheaper than burning. Spam apps basically come from resource markets, but the current resource markets are normally p2p model, which is not flexible for price adjustment.
> 
> The most critical point of this proposal is to propose a standard how to how to implement a resource rental market with smart contract, that make TRX liquidity staking can be tokenized. The resource market is just a by-product of it. Also, the standard resource market can be integrated with DeFi applications. After this kind of resource market supports energy renting, the standard smart contract can adjust price more reasonably than current p2p ones. Energy renting will also promote a more prosperous ecology which can make TRON better.

Bro, do you even realize what you are saying. p2p is the best kind of system anyone in decentralized world can hope for. It is literally one of the core ideologies of crypto currencies. You are saying we should create a centralized standard smart contract to regulate energy rental price (no doubt by TRON foundation) instead of letting TRON users trade with each other directly. This statement is so over the top in its anti-crypto sentiment that I don't even know how to respond to it :anguished:

Also, what do you mean by "**the current resource markets are normally p2p model, which is not flexible for price adjustment**"? Flexible for who?? Anyone who wants to sell energy can sell at any price they want. That is about as flexible as it gets. It sounds like you are not happy with how people are freely trading energy with each other in an open market setting and want to regulate it so only a select few can make money from it. Lol, we have seen this movie before and we know who the usual culprits are :laughing:

And,  you say "Energy renting will also promote a more prosperous ecology which can make TRON better", well, duh! that is what's happening right now where everyone has the freedom to sell energy to anyone. You are proposing a system to regulate it and make it more restrictive by unnecessarily tokenizing staked trx. Not a good idea.

**Comment by raymondliu0711** [comment]
> 



> > > > @otakuinny I noticed that the resource model has been adjusted in #467 and some instructions have been added to the TVM to allow contract accounts to perform some of the operations in the new stake system as well as EOA accounts. However, these are only upgrades and innovations in the chain itself. The TRON network does not provide stake tokenization and liquidity design for the old and new stake systems. This is the main problem that this proposal is trying to solve. The discussion is open and we welcome your opinions.
> > > 
> > > 
> > > I'm so sick and tired of hearing about resource rental market. Renting out tron resources is a by-product of an address being able to delegate resources to another address. Too much attention is being paid to the resource rental process. Instead of encouraging it with peoposals like these, we should be discouraging it. Renting resources prevents users from burning trx which contributes to trx inflation which results in lower price. It is actually healthy for TRON to burn trx. This will decrease the circulating supply and the resultant price increase will attract more people to the chain. And another thing, right now the majority of daily transactions are just spam and/or scam transactions. All these scammers rent energy which is why they are able to make so many transactions. I don't understand why you want to make it even more easier for scammers to send more scam transactions while at the same time pushing the price of trx lower on account of not burning any trx for transactions.
> > > There is already a vibrant rental Markey and every Tom, Dick and Harry sells their energy on Telegram and other places. There's no need to make it any more easier for scammers to rent energy than it is right now.
> > > Please stop with proposals like these that hurt tron and try to think about how you can make TVM better. Seeing a lot of errors lately.
> > 
> > 
> > Now freezing to get energy is much cheaper than burning. Spam apps basically come from resource markets, but the current resource markets are normally p2p model, which is not flexible for price adjustment.
> > The most critical point of this proposal is to propose a standard how to how to implement a resource rental market with smart contract, that make TRX liquidity staking can be tokenized. The resource market is just a by-product of it. Also, the standard resource market can be integrated with DeFi applications. After this kind of resource market supports energy renting, the standard smart contract can adjust price more reasonably than current p2p ones. Energy renting will also promote a more prosperous ecology which can make TRON better.
> 
> Bro, do you even realize what you are saying. p2p is the best kind of system anyone in decentralized world can hope for. It is literally one of the core ideologies of crypto currencies. You are saying we should create a centralized standard smart contract to regulate energy rental price (no doubt by TRON foundation) instead of letting TRON users trade with each other directly. This statement is so over the top in its anti-crypto sentiment that I don't even know how to respond to it 😧
> 
> Also, what do you mean by "**the current resource markets are normally p2p model, which is not flexible for price adjustment**"? Flexible for who?? Anyone who wants to sell energy can sell at any price they want. That is about as flexible as it gets. It sounds like you are not happy with how people are freely trading energy with each other in an open market setting and want to regulate it so only a select few can make money from it. Lol, we have seen this movie before and we know who the usual culprits are 😆
> 
> And, you say "Energy renting will also promote a more prosperous ecology which can make TRON better", well, duh! that is what's happening right now where everyone has the freedom to sell energy to anyone. You are proposing a system to regulate it and make it more restrictive by unnecessarily tokenizing staked trx. Not a good idea.

The TRC is decentralized and it is a smart contract standard like TRC-20 that anyone can implement.  

Also, there may be a problem that p2p trading needs to guarantee the interests of both parties while transactions on resource market with standard is open and transparent. Standard resource markets can coexist with p2p and people have the freedom to choose among them.

**Comment by musknuibility** [comment]
Anyone can stake TRX to the contract and rent energy from contracts, right?

**Comment by otakuinny** [comment]
> Anyone can stake TRX to the contract and rent energy from contracts, right?

You can't stake TRX to a contract address. In order to rent energy from a contract, the contract has to have TRX in it. Also, contracts can't delegate resources yet.

**Comment by otakuinny** [comment]
> > 
> 
> > > > > @otakuinny I noticed that the resource model has been adjusted in #467 and some instructions have been added to the TVM to allow contract accounts to perform some of the operations in the new stake system as well as EOA accounts. However, these are only upgrades and innovations in the chain itself. The TRON network does not provide stake tokenization and liquidity design for the old and new stake systems. This is the main problem that this proposal is trying to solve. The discussion is open and we welcome your opinions.
> > > > 
> > > > 
> > > > I'm so sick and tired of hearing about resource rental market. Renting out tron resources is a by-product of an address being able to delegate resources to another address. Too much attention is being paid to the resource rental process. Instead of encouraging it with peoposals like these, we should be discouraging it. Renting resources prevents users from burning trx which contributes to trx inflation which results in lower price. It is actually healthy for TRON to burn trx. This will decrease the circulating supply and the resultant price increase will attract more people to the chain. And another thing, right now the majority of daily transactions are just spam and/or scam transactions. All these scammers rent energy which is why they are able to make so many transactions. I don't understand why you want to make it even more easier for scammers to send more scam transactions while at the same time pushing the price of trx lower on account of not burning any trx for transactions.
> > > > There is already a vibrant rental Markey and every Tom, Dick and Harry sells their energy on Telegram and other places. There's no need to make it any more easier for scammers to rent energy than it is right now.
> > > > Please stop with proposals like these that hurt tron and try to think about how you can make TVM better. Seeing a lot of errors lately.
> > > 
> > > 
> > > Now freezing to get energy is much cheaper than burning. Spam apps basically come from resource markets, but the current resource markets are normally p2p model, which is not flexible for price adjustment.
> > > The most critical point of this proposal is to propose a standard how to how to implement a resource rental market with smart contract, that make TRX liquidity staking can be tokenized. The resource market is just a by-product of it. Also, the standard resource market can be integrated with DeFi applications. After this kind of resource market supports energy renting, the standard smart contract can adjust price more reasonably than current p2p ones. Energy renting will also promote a more prosperous ecology which can make TRON better.
> > 
> > 
> > Bro, do you even realize what you are saying. p2p is the best kind of system anyone in decentralized world can hope for. It is literally one of the core ideologies of crypto currencies. You are saying we should create a centralized standard smart contract to regulate energy rental price (no doubt by TRON foundation) instead of letting TRON users trade with each other directly. This statement is so over the top in its anti-crypto sentiment that I don't even know how to respond to it 😧
> > Also, what do you mean by "**the current resource markets are normally p2p model, which is not flexible for price adjustment**"? Flexible for who?? Anyone who wants to sell energy can sell at any price they want. That is about as flexible as it gets. It sounds like you are not happy with how people are freely trading energy with each other in an open market setting and want to regulate it so only a select few can make money from it. Lol, we have seen this movie before and we know who the usual culprits are 😆
> > And, you say "Energy renting will also promote a more prosperous ecology which can make TRON better", well, duh! that is what's happening right now where everyone has the freedom to sell energy to anyone. You are proposing a system to regulate it and make it more restrictive by unnecessarily tokenizing staked trx. Not a good idea.
> 
> The TRC is decentralized and it is a smart contract standard like TRC-20 that anyone can implement.
> 
> Also, there may be a problem that p2p trading needs to guarantee the interests of both parties while transactions on resource market with standard is open and transparent. Standard resource markets can coexist with p2p and people have the freedom to choose among them.

So you are suggesting TRON create a completely new standard TRC-484 just to fit the specific use case of resource rental market? So, if I have an idea for a dapp tomorrow that needs some flexibility on the part of TRX token, can I create a standard TRC-XXX and force TRON foundation to implement it 😆

`Also, there may be a problem that p2p trading needs to guarantee the interests of both parties`
Not sure what problem you are referring to. Besides, what you are proposing is exactly how the rental market works right now. There are pools (contract in your proposal) that TRON users can join with their TRX and receive the revenue generated from these pools proportionate to the TRX they supplied. **Some of these pools are actually way better than what you are proposing because the users don't even have to send their TRX to the pool. They can just give permissions to the pool account to freeze. This is much safer than sending TRX to a contract.** No need to create an unnecessary new standard for a specific use case and make TRON look like a laughing stock.

Just because several users are freely trading TRON resources now doesn't mean you have to create an standard for it. There are a lot of ponzi scams on TRON like BSG, TRON Grace, OxCash... Are you going to propose a TRC standard for a ponzi dapp next 😆.

**Comment by otakuinny** [comment]
> > Anyone can stake TRX to the contract and rent energy from contracts, right?
> 
> Yes, as you understand.

Wrong! In your proposal you "send" trx to contract, not stake it.

**Comment by musknuibility** [comment]
> You can't stake TRX to a contract address. In order to rent energy from a contract, the contract has to have TRX in it. Also, contracts can't delegate resources yet.

It seems that the contract helps users complete the staking and resource delegating

**Comment by otakuinny** [comment]
> > 
> 
> Then the contract will freeze
> 
> > > > Anyone can stake TRX to the contract and rent energy from contracts, right?
> > > 
> > > 
> > > Yes, as you understand.
> > 
> > 
> > Wrong! In your proposal you "send" trx to contract, not stake it.
> 
> "Stake" means the contract will freeze deposited TRX after receiving.

Yes, but you need to clarify that the users have to first send their trx to the contract. Otherwise, they'll mistakenly think that just by interacting with a contract they can stake their trx directly from their account.

**Comment by otakuinny** [comment]
> > You can't stake TRX to a contract address. In order to rent energy from a contract, the contract has to have TRX in it. Also, contracts can't delegate resources yet.
> 
> It seems that the contract helps users complete the staking and resource delegating

No, it does not. You first need to send your trx to the contract. Then the contract will delegate resources from the contract. It is not your trx anymore because you sent it to a contract. In exchange, you'll get some trc20 tokens but there is no guarantee that the contract is not malicious and won't steal your trx. This is very risky as anyone can create a contract with this standard and add their own separate functions to steal trx.

**Comment by musknuibility** [comment]
This is more like defi, funds are staked to the contract, obviously,  it requires the contract to be open source and audited by a professional organization.

**Comment by otakuinny** [comment]
> This is more like defi, funds are staked to the contract, obviously, it requires the contract to be open source and audited by a professional organization.

Audits are worthless. There are even fake audit firms that'll certify if you pay them enough. Also, the BSG dapp that scammed more than 25,000 people in India was audited and had its code open sourced.

**Comment by sunflower-sun** [comment]
This is necessary to have a such standard because it is a very common DAPP scenario. By staking TRX in a such pool, Staker can not only obtain staking reward, and at the same time, stake tokens they receive can alleviate their lack of liquidity caused by staking. So it's a good proposal from any side.

**Comment by m-o-m12** [comment]
> > This is more like defi, funds are staked to the contract, obviously, it requires the contract to be open source and audited by a professional organization.
> 
> Audits are worthless. There are even fake audit firms that'll certify if you pay them enough. Also, the BSG dapp that scammed more than 25,000 people in India was audited and had its code open sourced.

We cannot refuse publish standards because of individual cases.

**Comment by nobodywhen** [comment]
Tokenization is good idea, can further motivate users to stake,  help to stabilize the value of TRX.

**Comment by LauraYH** [comment]
From the diagram, it is clear that the idea of tokenization is to maximize the utilization of the TRX. The discussion of separating vote power and resources has been going on for a long time, and the proposal seems more implementable. I am not saying tokenization is the only reasonable way to apart TRON power from energy and bandwidth, a new TRC-20 token may not be the best practice of it; however, I prefer a rental market more than the current mode. 

Since the TRX would be deposited to a contract, and governed by the DAO, the proposal currently is not detailed enough. Would like to see more.

**Comment by Jackmrshen** [comment]
> > > You can't stake TRX to a contract address. In order to rent energy from a contract, the contract has to have TRX in it. Also, contracts can't delegate resources yet.
> > 
> > 
> > It seems that the contract helps users complete the staking and resource delegating
> 
> No, it does not. You first need to send your trx to the contract. Then the contract will delegate resources from the contract. It is not your trx anymore because you sent it to a contract. In exchange, you'll get some trc20 tokens but there is no guarantee that the contract is not malicious and won't steal your trx. This is very risky as anyone can create a contract with this standard and add their own separate functions to steal trx.

I think when TIP https://github.com/tronprotocol/tips/issues/467 takes effect, any one can stake TRX for energy and delegate it to others. I agree with you that p2p method for energy renting is working well for individual now, just that when it comes to a overall scope, a standard market for renting will involve more participants, it is something like local optimal solution and global optimal solution. I would say i am not denying this new proposal. And maybe tokenize the staked TRX is just a security way to avoid malicious smart contract, it is easier for users to validate. Indeed there is much more to do for the community, maybe if you specify some errors you met, it would also be big contribution.

**Comment by otakuinny** [comment]
I don't think anyone fully understands what this proposal involves. The standard proposed us useless because it does absolutely nothing. When staking from contract feature is enabled, anyone can create a contract, create a trc20 token and make their own resource rental dapp. But that is only like 20% of the dapp. They still need to have a server with a lot of code that needs to maintain all the freezes information and unfreeze expired freezes on a schedule. So, to all those thinking this standard is going to magically help you create a resource rental dapp, I got bad news for you 😆.

Conpare this to a trc20 token standard which is almost self contained and requires little to no server coding necessary. Unlike a trc20 standard, this 484 standard alone doesn't do anything without a backend server infrastructure, database to store all the freezes information and job to unfreeze the expired freezes. 

This is why I labeled it useless cos you can already do this without a contract. And, what is this bs about a DAO. I swear people just keep using that Abbreviation without knowing the first thing about it. There would be no dao governance in a simple dapp like a resource rental market. I mean, there could be but it will massively complicated for a very little payoff.

**Comment by otakuinny** [comment]
> There is no need to have a backend server, because it is a DAPP, it can be realized by smart contracts only and it is not controlled by any centralized server.

How do you think the freezes are unfrozen, and who unfreezes them and when 😆

**Comment by raymondliu0711** [comment]
The specific implementation details are still under investigation and discussion. Of course, there are many ways to realize it and backend server is not necessary.  One possible solution is unfreezing happens when "exit" is called. There can also be more interfaces for users to query their deposit status.

**Comment by otakuinny** [comment]
> The specific implementation details are still under investigation and discussion. Of course, there are many ways to realize it and backend server is not necessary. One possible solution is unfreezing happens when "exit" is called. There can also be more interfaces for users to query their deposit status.

If backend server is not necessary, then who calls the exit function, and from where, and when. Obviously, the user renting the resource is not going to call it because he will receive free energy if he doesn't. 

Like I said, this is a useless standard because it requires the support of a backend server.

**Comment by hitlxy** [comment]
At present, there are a lot of liquidity staking applications on major public chains, and they brings many benefits to both users and chains. Especially for Proof-of-Stake blockchains like TRON, the larger staking amount will ensure the security of the network, so TRON needs this kind of applications. And the new stake model will lead to an increase of the liquid staking DAPP on TRON. So this tip is necessary. 

Because of TRON's special resource model, we can not only get the staking rewards but also obtain free bandwidth/energy from staking. So energy must have its own market. Due to the new stake model, the liquid staking DAPP also can provide energy market, and energy market will change from centralized app to de-centralized.
  
Staking tokens are mentioned in this standard, if they can used in the defi projects in the future, they can bring more other rewards to token holders. It's worth looking forward.

**Comment by otakuinny** [comment]
> At present, there are a lot of liquidity staking applications on major public chains, and they brings many benefits to both users and chains. Especially for Proof-of-Stake blockchains like TRON, the larger staking amount will ensure the security of the network, so TRON needs this kind of applications. And the new stake model will lead to an increase of the liquid staking DAPP on TRON. So this tip is necessary.
> 
> Because of TRON's special resource model, we can not only get the staking rewards but also obtain free bandwidth/energy from staking. So energy must have its own market. Due to the new stake model, the liquid staking DAPP also can provide energy market, and energy market will change from centralized app to de-centralized.
> 
> Staking tokens are mentioned in this standard, if they can used in the defi projects in the future, they can bring more other rewards to token holders. It's worth looking forward.

Everything you said can be done when the stake from contract feature is enabled. This standard does absolutely nothing. Also, for a resource rental market from contract to work, you need a backend server, which makes it centralized. 

This is what happens when people with half knowledge try to create proposals.

**Comment by Ademillery** [comment]
> > The specific implementation details are still under investigation and discussion. Of course, there are many ways to realize it and backend server is not necessary. One possible solution is unfreezing happens when "exit" is called. There can also be more interfaces for users to query their deposit status.
> 
> If backend server is not necessary, then who calls the exit function, and from where, and when. Obviously, the user renting the resource is not going to call it because he will receive free energy if he doesn't.
> 
> Like I said, this is a useless standard because it requires the support of a backend server.

As I go through the the community discussion, I also concern about the detail of the technical realization of this proposal, I wonder oracle may  be implemented to meet this requirement. However, except for these details, basically I agree with the majority that the idea to increase energy utilization is beneficial for most of users, and this proposal will scale up the market by dAPPs, I expect to see further progress of this idea, then we could check whether the technical route is reasonable together.

**Comment by bractbright** [comment]
Does TRC484 allow the resource market to integrate other DAPPs? If so, TRC484 should provide some read-only API, such as query how much energy I have in the market.

**Comment by raymondliu0711** [comment]
> Does TRC484 allow the resource market to integrate other DAPPs? If so, TRC484 should provide some read-only API, such as query how much energy I have in the market.

Thank you for your suggestion. 

Yes, TRC484 will provide such query APIs that can make resource market better integrated with other DApps.

**Comment by strxfinance** [comment]
Do you believe the TRC484 interface provided is adequate to serve as a resource marketplace?
Could you please provide an example TRC-484 contract ?

**Comment by otakuinny** [comment]
> Do you believe the TRC484 interface provided is adequate to serve as a resource marketplace? Could you please provide an example TRC-484 contract ?

The changes in stake2.0 make the TRC484 interface redundant. After stake2 is live, you can just freeze trx from smart contracts.

**Comment by Ademillery** [comment]
I think it would be enough. The purpose of this TIP is to provide standard TRC-484 interface,  if I need others, I will just develop customized interfaces based on my service.
