### ISSUE TITLE
TRC57: Allow burning TRX in deployer account for contract triggering energy payment

### ISSUE THREAD

**Issue by taihaofu** [tronprotocol/tips#57]
```
tip: 57
title: TRC57: Allow burning TRX in deployer account for contract triggering energy payment
author: Taihao Fu <taihao.fu@gmail.com>
discussions to: https://github.com/tronprotocol/TIPs/issues/56
category: TRC
status: draft
created: 2019-09-17
```

# Simple Summary
This doc present a new option for contract owner pay for their contract user energy consumption.

# Abstract
Current design allow contract deployer/owner to to pay none/part/all energy fee for their customer which is a way to attract more customer to participate in their contract. However, only frozen energy is allowed for the payment. In current TRON network, frozen energy is expensive since the global frozen energy is raising. Some contract owner thought it is more convenient by simply consuming their TRX in their account for their customer rather than use “free" frozen energy which cost lot of frozen TRX to gain.

# Motivation
Contract owner hope to use TRX burning mechanism directly for their user consumption.

# Specification
1. We have a parameter called `consume_user_resource_percent` which represent the percentage user should pay for the contract calling. The rest part is the target fee we would like to discuss in this TRC.
2. In current design, only energy gain from frozen TRX in contract deployer account can be use to pay the developer side consumption.  
3. When the frozen energy is used up, we can implement a new logic to burn TRX in deployer’s account if the deployer willing to consume its TRX. 

# Advantages:

1. Expensive frozen energy problem can be resolved.

2. TRX burning can be a convenient way and a flexible way for deployer to set the strategy. 

3. It would be a good way to attract more customer for developer's contract. 

# Downsides:

1. It’s unsafe. Anyone can trigger a fallback function without any punishment and deployer has to suffer from all the consequences(TRX consuming). 

2. We will break the law that nobody should let the TRX in someone else account to reduce. Now, this kind of attacking can not be avoid.

**Comment by jacklcz** [comment]
+1

**Comment by Leorexo** [comment]
I am against this proposal. As a developer, this means a greater risk to me. If you enable this feature for smart contracts, you may continue to use the developer's trx. If there is a vulnerability in the smart contract, the account will be unavailable and will have unpredictable consequences in the case of a continuous attack.

**Comment by reverde** [comment]
I can understand some contract creator may have this kind of requirement due to lacking of frozen energy. But, I doubt the possibility by simply consuming a creator's account balance. 

I don't think any contract creator is willing to let other people use their TRX directly especially the program language they use is the "unsafe" Solidity language. We all know Solidity has its own shortage for safety problems. We can easily create an fallback attack which has nothing to do with the target contract but just consuming its creator's energy even today. If you open burning TRX up, how can you guarantee the safety for creator's assets? In this case, I really don't think any developer dare to use this new feature.

I don't think it has a practical solution as long as you are using Solidity language, unless you change your chain a lot(but also I think it is meaningless ).

**Comment by Leorexo** [comment]
> I can understand some contract creator may have this kind of requirement due to lacking of frozen energy. But, I doubt the possibility by simply consuming a creator's account balance.
> 
> I don't think any contract creator is willing to let other people use their TRX directly especially the program language they use is the "unsafe" Solidity language. We all know Solidity has its own shortage for safety problems. We can easily create an fallback attack which has nothing to do with the target contract but just consuming its creator's energy even today. If you open burning TRX up, how can you guarantee the safety for creator's assets? In this case, I really don't think any developer dare to use this new feature.
> 
> I don't think it has a practical solution as long as you are using Solidity language, unless you change your chain a lot(but also I think it is meaningless ).

Agree with your point of view. The burning developer's trx needs a new charging mechanism that is different from the current one, rather than simply changing the energy generated by the consumption freeze to consuming trx. This requires a lot of work, and it also requires extensive input from the community, especially developers.

**Comment by taihaofu** [comment]
@reverde @Leorexo The pain-point here is, it is hard to find a proper solution to prevent TRX burning fallback attacking. If we really need do so we need make an work around for this. But, currently it seems hard to do so.

**Comment by yanghang8612** [comment]
We do not have further implemention plan.
So we close this issue.
