### ISSUE TITLE
Proposal: Decrease the transaction fee

### ISSUE THREAD

**Issue by SevenPie-R58zz** [tronprotocol/tips#668]
## Simple Summary

Decrease the transaction fee to increase the transaction volume on the TRON network.

## Motivation

The transaction fees on the TRON network have been increased several times in the past few years. It has promoted the burning of fees and increased the deflation rate, at the same time, the staking rate has also increased significantly, further consolidating the security of the network.

The TRON network is well known for its low transaction fees. After several fee adjustments, the fee advantage is currently weakening. The higher network transaction fees play an important role in the security and stability of the TRON network, but at the same time, it also increases the cost of using dApps and limits the growth of transaction scale.

It is recommended to appropriately reduce transaction fees to ensure the competitiveness of the TRON network in terms of fees, while further stimulating the growth of the overall transaction scale.

## Specification

Decrease the energy unit price from 420 sun to 210 sun.

Increase the `max_factor` parameter in the dynamic energy model from 1.2 to 3.4, and meanwhile increase the `threshold` parameter in the dynamic energy model from 3,000,000,000 to 5,000,000,000.

More details about the explanation of parameters in the dynamic energy model, please refer to [here](https://developers.tron.network/docs/resource-model#dynamic-energy-model).

## Background

As can be seen from the figure below, after the [#51](https://tronscan.org/#/proposal/51) proposal in February 2021, the [#71](https://tronscan.org/#/proposal/71) proposal in October 2021, and the [#79](https://tronscan.org/#/proposal/79) proposal in December 2022, the transaction fee has been successively increased, the TRX staking rate rises rapidly. In particular, the meme market in the TRON ecosystem has been very activated recently, and the demand for resources has increased rapidly. The TRX staking rate has also risen significantly in the short term.

The continued increase in the staking rate has created a precondition for reducing the transaction fee. At the same time, reducing the transaction fee can also make the short-term large fluctuations in the staking rate return to stability.

<img width="875" alt="image" src="https://github.com/user-attachments/assets/a41d0de1-bf78-48f1-a3bf-7d87e21f8f42">

As can be seen from the figure below, after the #51 proposal to increase the transaction fee in February 2021 came into effect, the inflation of the TRON network was greatly alleviated. After the #71 proposal to increase the transaction fee in October 2021 came into effect, the TRON network quickly changed from an inflationary model to a deflationary model. The #79 proposal in December 2022 increased the transaction fee again, and the deflation rate of the TRON network increased significantly. The net TRX supply continued to decline, which played a positive role in the TRX price market.

At the same time, continued deflation has also created a precondition for reducing transaction fees. Appropriate reduction of transaction fees will not have a big impact on the deflationary model.

<img width="1090" alt="image" src="https://github.com/user-attachments/assets/3fd8459c-73b0-44a9-a9ff-493f6b8b2c86">

### Effect of fee adjustments on deflation

Based on the on-chain data analysis, it is expected that the deflationary situation of the entire network will not change significantly.

The current deflation status of the entire network is shown in the list below:

|  | Estimation based on data from the last week | Estimation based on data from the last month | Estimation based on data from the last 3 months | Estimation based on data from the last 6 months|
| -------- | -------- | --------|---| ---|
| Average daily burning volume  | 20,228,575 TRX | 12,836,735 TRX | 11,047,824 TRX | 11,203,942 TRX |
| Total annual burning volume of the entire network | 7,383,429,784 TRX  | 4,685,408,359 TRX  | 4,032,455,926 TRX  | 4,089,438,868 TRX  |
| Total annual net increase of TRX | -5,535,630,424 TRX | -2,837,608,999 TRX | -2,184,656,566 TRX | -2,241,639,508 TRX |
| Deflation rate | 6.38% | 3.27%  | 2.52% | 2.58% |

The expected deflation status of the entire network after the proposal is enabled is shown in the list below:

|  | Estimation based on data from the last week | Estimation based on data from the last month | Estimation based on data from the last 3 months | Estimation based on data from the last 6 months|
| -------- | -------- | --------|---| ---|
| Average daily burning volume  | 17,379,705 TRX | 11,740,224 TRX | 10,613,799 TRX | 10,887,747 TRX |
| Total annual burning volume of the entire network | 6,343,592,408 TRX  | 4,285,181,833 TRX  | 3,874,036,813 TRX  | 3,974,027,750 TRX  |
| Total annual net increase of TRX | -4,495,793,048 TRX | -2,437,382,473 TRX | -2,026,237,453 TRX | -2,126,228,390 TRX |
| Deflation rate | 5.18% | 2.81%   | 2.33% | 2.45% |

### Effect on transaction volume

The reduction of transaction fees will improve the competitiveness of the TRON network in terms of fees, attracting more users and dApps to join, thereby increasing overall transaction volume on the TRON network.

**Comment by WindsofChange92** [comment]
I agree.

Smart contract TXN fees need to drop. Then the energy system will be alleviated allowing to stake less on SunPump, freeing up the pressure on the energy system for everyone.  SunPump can then adjust its on-contract subsidy as well to push more users into an acceptable burn. 

This also allows for TRX prices to continue upwards with more adoption. With more TRX price appreciation more fee reduction will be required. 

Dropping smart contract fees will also indirectly make TRX staking energy more effective allowing more smart contract txn per energy cost.

**Comment by dwjorgeb** [comment]
Agreed. 

Reducing the cost of energy and disabling the USDT tax (aka "dynamic energy model") is the way to go.

**Comment by undershanon** [comment]
Agreed!  Will the energy price and bandwidth price both decrease?

**Comment by JefianDenis** [comment]
Disagree!
As a result of removing the energy burning mechanism or significantly reducing the burning price, many energy market and sellers will leave the network. 
As example, TEM, feee, neee, tronify, justlend.
There is a certain amount that is distributed in their favor now. If it is reduced, much fewer people will be willing to spend time on activity in the Tron network. And this is regular activity, unlike the launch of Sun's memecoins. Nothing will happen to people, they will move to other networks. The problem is that the Tron network will become much less decentralized.

**Comment by ibnzUK** [comment]
Agree 100%

For developers growing fees on the network are the biggest hurdle and head scratch. 
The same happens with increased network token (TRX) prices and fee values in Fiat. 

Dropping it down is plausible, this would attract more developers and incentivise dapps from other (more expensive) chains to be migrated.

**Comment by Homaxchange** [comment]
Agreed.

**1. Alleviating Network Pressure and Promoting Adoption**

**Reduced Energy Consumption:** Lowering transaction fees would decrease the energy required for smart contract interactions, easing the strain on the network and reducing the need for users to stake large amounts of TRX for energy.

**Increased Accessibility:** Lower fees would make the Tron network more attractive to developers and users, especially those with smaller budgets, promoting wider adoption.

**2. Stimulating TRX Price Appreciation**

**Increased Demand:** As more users and dApps migrate to the Tron network due to lower fees, the demand for TRX would likely increase, driving up its price.

**Positive Feedback Loop:** Rising TRX prices could incentivize further fee reductions, creating a positive feedback loop that benefits the entire ecosystem.

**3. Improving Network Efficiency and Competitiveness**

**Enhanced User Experience:** Reduced transaction fees would result in faster and more affordable transactions, improving the overall user experience.
**Attracting More Developers:** Lower fees would make the Tron network a more attractive platform for developers to build dApps, fostering innovation and competition.

**4. Balancing Deflationary Pressure**

**Increased Transaction Volume:** While reducing fees might initially decrease the deflationary pressure, the resulting increase in transaction volume could offset this effect.
**Strategic Adjustments: The** network could be fine-tuned to maintain a desired deflationary rate through adjustments to other parameters, such as the energy supply or staking rewards.
Conclusion

Reducing smart contract transaction fees presents a promising strategy for the Tron network. By alleviating network pressure, stimulating TRX price appreciation, improving efficiency, and balancing deflationary pressures, this approach could significantly enhance the network's competitiveness and long-term sustainability.

**Comment by simbadMarino** [comment]
Agree!
We need to decrease transaction costs, especially this is positive due to the price increase of TRX and for individuals and entities not willing or knowing how to rent energy or stake TRX for resources. This proposal should be implemented together with #667 to overcome the current situation of high fees on TRON effectively.

We are already losing market share for micro payments(<$100) and medium size ($100 to $1000) payments on Stablecoins to chains like BNB and Matic and Solana as shown in the followin chart:

![image](https://github.com/user-attachments/assets/15fc0048-d17d-49d1-bb80-93b7ee766ad8)

We are at a critical point now for mass adoption; at this point in time, I'd suggest **decreasing fees by at least 10x.**

**Comment by Moneyversac** [comment]
if TRX goes to let's say 0.30$ in best case and stays there, we will have the problem that the chain will become too expensive for people living in emerging countries.
So if your goal is also to increase the price of TRX, there must be a solution in place.
No to keep the burning rate stable and the end user happy:
How about implementing a flexible energy price?
I mean the price of it would reduce or increase according to the TRX price.

Scenario 1:
TRX price goes up 100% from 0.10$ to 0.20$
Energy prices goes down accordingly to 50% of what it cost at 0.10$ to keep the exact same energy price

Scenario 2:
TRX price goes down 50% from 0.10$ to 0.05$
Energy price increases 100% in order to make it the same cost as it was at 0.10$

You could have a basecost that changes according to actual TRX price.

Maybe that would be an interesting solution.

**Comment by CommunitySR** [comment]
Partially agree with the statement. 

1 . It is said on the proposal that it might decrease the staking rate . Most tron users do not stake their TRX to do transactions they stake for energy to participate in the best running bussiness model TRON has which no other chain currently has which is Energy rental . Decreasing the fee will not make people unstake and burn instead . 

2. A result of decreasing the fee to much might see the above named industry collapse and users might start looking for better passive earning abilities elsewhere . 

3. Decrease the fee to far might hurt the current deflation rate of the network as most is burned through the use of USDT and in the worst case it could make tron inflationary again and we end up increasing the fee again. 

4. Currently there are 40 billion energy unused in the Sunpump contract , as the hype is slowly fading away there are less transactions then when it was firstly launched . Trondao should monitor the amount of energy needed to keep te platfom running and needs to release or add energy based on the needs . This will already take pressure off the current extreme high demand of energy for transactions and makes way for Energy platforms to offer cheaper solutions to people so they have a 80% discount on their current transaction fees . 

I do agree with the increasing price of TRX the current fee level is not sustainable and thereby also agree with the statement made by Moneyversac above my comment that it should be researched if a dynamic energy model based on the price of TRX is possible.  Meanwhile heavily educating and assist in promoting the Energy platforms offer for people to decrease their fees by another 80%

**Comment by simbadMarino** [comment]
@SevenPie-R58zz , do we have any ETA to push this for SRs to vote? Also, I didn't see any specifics on how much you are proposing as reduction.
We need a considerable overall fee reduction, happy to hear back from you considering community feedback and on chain analysis :) 

Thanks!

**Comment by KrisdiaPaul** [comment]
I think to specify the proposal, one good approach is to reduce the unit energy price, which has been raised several times to 420 sun. Reducing this will benefit the majority of transactions on the TRON network.

**Comment by MannGates** [comment]
Reducing energy price is an effective way, burning for energy accounts for the most of the cost. If the energy price could be changed to 300sun, it would be good news to the community.

**Comment by souppopnix** [comment]
Agree, energy takes the most of trc20 transaction fee, reducing the energy unit price will directly decrease the most transaction fees.

**Comment by ChuffinCelery72** [comment]
> I think to specify the proposal, one good approach is to reduce the unit energy price, which has been raised several times to 420 sun. Reducing this will benefit the majority of transactions on the TRON network.

Don't do that, you are misleading the community by simply decreasing the energy price. Agree with the comment from communitysr, reducing the energy price too much will harm the deflation of TRON, even make it inflation again.

**Comment by CooperDepp** [comment]
Lowering transaction fees is good, but lower energy price means less burning of TRX, only reducing the energy price will eventually make TRX inflation and it's dangerous to the TRX price, don't agree to reduce energy price!

**Comment by ChuffinCelery72** [comment]
> Lowering transaction fees is good, but lower energy price means less burning of TRX, only reducing the energy price will eventually make TRX inflation and it's dangerous to the TRX price, don't agree to reduce energy price!

I was thinking that if we want the transaction fees to be cheaper, but meanwhile we hope to keep deflation to make TRX rise. The only possible way is to increase the energy consumption of part of transactions while keep others remains the same. So that we would at least make part of transactions cheaper.

**Comment by ChuffinCelery72** [comment]
One good option is to enlarge the punishment parameter in the dynamic energy mode. On one hand, it will increase the energy burning, and encourage more fairly energy allocation, on the other hand, it makes other transaction fees cheaper. That's the best way to solve the situation.

**Comment by KrisdiaPaul** [comment]
Reducing energy price and find a way to increase TRX burning sounds reasonable considering the TRX market. One more benefit is that burning TRX for energy becomes cheaper and staking TRX for energy would decrease, and it could release demand pressure for energy.

**Comment by CooperDepp** [comment]
The specification part indicate that the transaction fees of dApps have a reduction of about 50%, and other transaction fees almost remain the same, it's acceptable.

**Comment by rrouk** [comment]
TronDAO is shooting itself in the foot, cutting the branch it's sitting on in pursuit of Solana's success.

**Comment by otakuinny** [comment]
Lol, so many people offering suggestions as if it really matters. Even though TRON dao calls it a proposal that is open for discussion, it is actually quite the opposite. It is already decided and will take effect in a couple of days when all "inDepEndent cOmMUnity" SRs vote to pass it magically.

Any one who's been in TRON for a few years knows this and will not waste time with offering suggestions lol.

**Comment by aghamir** [comment]
This is ridiculous. Mr Sun use his power to overtake most of energy for himself. After that community propose a TIP which is only decrease Mr Sun's project contracts and doesn't fix high fee in USDT. Change the title to decrease Mr Sun's transactions fees.

**Comment by dwjorgeb** [comment]
So, the proposal increases the dynamic fee threshold from 3B to 5B energy, just enough for the SunPump crap to be excluded, while increasing (yet again) the blockchain fees for USDT...

**Comment by Abokil711** [comment]
[](url)
