### ISSUE TITLE
停止，owner权限运行

### ISSUE THREAD

**Issue by Hugosun3434** [tronprotocol/tips#685]
请问我的钱包被人操控了，有没有办法把owner权限更改回来？谢谢大家！

**Comment by laurenceja** [comment]
@Hugosun3434 For your account's permission changed, maybe you signed the account update transaction Inadvertently, or your privatekey has been leaked.  And due to the decentralized characteristic of blockchain, nobody can revert the online transaction, and nobody can change the account permission again except the person who has the owner permission.
