### ISSUE TITLE
Proposal to remove plaintext inclusion of private key in virtual machine on which node is running

### ISSUE THREAD

**Issue by calchulus** [tronprotocol/tips#86]
In this command that we have to send (which includes the private key) in plain text in setting up the java full node,

1. is it possible to avoid having to send this private key at all or keep it on this virtual machine on which the node is running? 
2. if it is absolutely necessary to provide this key, is there a way to allow this command to work with the key held in some sort of encrypted file on this machine rather than in plain next?

Would be best to avoid private key being mentionedi n plaintext anywhere.

**Comment by jiangyy0824** [comment]
@calchulus You can use localwitnesskeystore.json instead of private key to launch your node.  The json is used to protect private key leakage.

Step1: Create localwitnesskeystore.json with wallet-cli. Please refer to https://github.com/tronprotocol/wallet-cli. Launch wallet-cli, and use "ImportWallet" command. it will ask you input password, please save it. Then ask you to input your private key. After you input the private key. Wallet-cli will generate a json file under Wallet folder. Rename it to "localwitnesskeystore.json".

Step2: Copy "localwitnesskeystore.json" to the same folder with  java-tron jar.
Step3: Edit your config file. Find the config item: "localwitnesskeystore", uncomment it. Below is the sample.

localwitnesskeystore = [
  "localwitnesskeystore.json"
]

Step4: Launch the fullnode,  for example.   
java -Xmx$xmx -XX:+UseConcMarkSweepGC -jar FullNode.jar --password xxxxxxxxxx  --witness -c config.conf

"xxxxxxxxxx" is the password saved in Step 1. 

If you still have any question.  Please join the gitter. https://gitter.im/tronprotocol/allcoredev

Thanks.

**Comment by zhaohong** [comment]
@calchulus   you can use the key, which only having the block producing permission as the command parameter.

**Comment by zk19862018** [comment]
About how to use multi-signature to protect your private key,
please refer to:
https://tronprotocol.github.io/documentation-en/mechanism&algorithm/multi-signatures/
If you have any further question, please join our gitter channel to discuss.
